version: '3.1'

services:

  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ogranada
      MYSQL_USER: ogranada
      MYSQL_PASSWORD: Mimamamemimamemimamimama123*
      MYSQL_ROOT_PASSWORD: jajaja123*

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1
